%%%%%%% combine monkeys %%%%%%%%%%
newmot.a = [cbs.summary.a.norm.mot mos.summary.a.norm.mot pus.summary.a.norm.mot qus.summary.a.norm.mot];
newmot.b = [cbs.summary.b.norm.mot mos.summary.b.norm.mot pus.summary.b.norm.mot qus.summary.b.norm.mot];
newmot.c = [cbs.summary.c.norm.mot mos.summary.c.norm.mot pus.summary.c.norm.mot qus.summary.c.norm.mot];

newvel.a = [cbs.summary.a.norm.vel mos.summary.a.norm.vel pus.summary.a.norm.vel qus.summary.a.norm.vel];
newvel.b = [cbs.summary.b.norm.vel mos.summary.b.norm.vel pus.summary.b.norm.vel qus.summary.b.norm.vel];
newvel.c = [cbs.summary.c.norm.vel mos.summary.c.norm.vel pus.summary.c.norm.vel qus.summary.c.norm.vel];

oldmot.a = [cbs.summary.a.norm.oldmot mos.summary.a.norm.oldmot pus.summary.a.norm.oldmot qus.summary.a.norm.oldmot];
oldmot.b = [cbs.summary.b.norm.oldmot mos.summary.b.norm.oldmot pus.summary.b.norm.oldmot qus.summary.b.norm.oldmot];
oldmot.c = [cbs.summary.c.norm.oldmot mos.summary.c.norm.oldmot pus.summary.c.norm.oldmot qus.summary.c.norm.oldmot];

oldvel.a = [cbs.summary.a.norm.oldvel mos.summary.a.norm.oldvel pus.summary.a.norm.oldvel qus.summary.a.norm.oldvel];
oldvel.b = [cbs.summary.b.norm.oldvel mos.summary.b.norm.oldvel pus.summary.b.norm.oldvel qus.summary.b.norm.oldvel];
oldvel.c = [cbs.summary.c.norm.oldvel mos.summary.c.norm.oldvel pus.summary.c.norm.oldvel qus.summary.c.norm.oldvel];

typeamot.a = [cba.summary.a.norm.mot moa.summary.a.norm.mot pua.summary.a.norm.mot qua.summary.a.norm.mot];
typeamot.b = [cba.summary.b.norm.mot moa.summary.b.norm.mot pua.summary.b.norm.mot qua.summary.b.norm.mot];
typeamot.c = [cba.summary.c.norm.mot moa.summary.c.norm.mot pua.summary.c.norm.mot qua.summary.c.norm.mot];

typeavel.a = [cba.summary.a.norm.vel moa.summary.a.norm.vel pua.summary.a.norm.vel qua.summary.a.norm.vel];
typeavel.b = [cba.summary.b.norm.vel moa.summary.b.norm.vel pua.summary.b.norm.vel qua.summary.b.norm.vel];
typeavel.c = [cba.summary.c.norm.vel moa.summary.c.norm.vel pua.summary.c.norm.vel qua.summary.c.norm.vel];


%%%%%%%% get the fits %%%%%%%%%%%
[newfit.a res jac] = nlinfit(newmot.a,newvel.a,'sigmoid',[.05 40]);
[newfit.ci.a] = nlparci(newfit.a,res,jac);

[newfit.b res jac] = nlinfit(newmot.b,newvel.b,'sigmoid',[.05 40]);
[newfit.ci.b] = nlparci(newfit.b,res,jac);

[newfit.c res jac] = nlinfit(newmot.c,newvel.c,'sigmoid',[.05 40]);
[newfit.ci.c] = nlparci(newfit.c,res,jac);

[oldfit.a res jac] = nlinfit(oldmot.a,oldvel.a,'sigmoid',[.05 40]);
[oldfit.ci.a] = nlparci(oldfit.a,res,jac);

[oldfit.b res jac] = nlinfit(oldmot.b,oldvel.b,'sigmoid',[.05 40]);
[oldfit.ci.b] = nlparci(oldfit.b,res,jac);

[oldfit.c res jac] = nlinfit(oldmot.c,oldvel.c,'sigmoid',[.05 40]);
[oldfit.ci.c] = nlparci(oldfit.c,res,jac);

% bin up the data
binsize = 1;
maxcutoff = 100;
bindex = [-inf 0:binsize:maxcutoff inf];

[jnk inda] = histc(typeamot.a,bindex);
[jnk indb] = histc(typeamot.b,bindex);
[jnk indc] = histc(typeamot.c,bindex);

for i = 1:length(bindex)
  typeamean.a(i) = mean(typeavel.a(find(inda == i)));
  typeamean.b(i) = mean(typeavel.b(find(indb == i)));
  typeamean.c(i) = mean(typeavel.c(find(indc == i)));
end

% figure 5

mintime = 0;
maxtime = 100;
spacer = .1;

h = figure

subplot(3,3,1)
hold on


plot(newmot.a,newvel.a,'k.','markersize',2,'markerfacecolor',[.6 .6 .6],'markeredgecolor',[.6 .6 .6]);

% plot the confidence intervals as a ribbon -- fit them first to use them
% as dimensions for successive rectangles
lowci = sigmoid(newfit.ci.a(:,2),[mintime:spacer:maxtime]);
highci = sigmoid(newfit.ci.a(:,1),[mintime:spacer:maxtime]);
main = sigmoid(newfit.a,[mintime:spacer:maxtime]);
errorbar(mintime:spacer:maxtime,main,lowci-main,highci-main,'k');


set(gca,'tickdir','out',...
  'box','off',...
  'xlim',[mintime maxtime],'xtick',[mintime:25:maxtime], ...
  'ylim',[0 1],'ytick',[0 .5 1], ...
  'PlotBoxAspectRatio',[1 1 1], ...
  'DataAspectRatioMode','auto', ...
  'FontName','Helvetica', ...
  'FontSize',12, ...
  'LineWidth',0.96, ...
  'TickLength',[.048 .048], ...
  'XTickMode','manual','YTickMode','manual','ZTickMode','manual','xlimmode','manual','ylimmode','manual','zlimmode','manual');

subplot(3,3,2)
hold on

plot(newmot.b,newvel.b,'k.','markersize',2,'markerfacecolor',[.6 .6 .6],'markeredgecolor',[.6 .6 .6]);

lowci = sigmoid(newfit.ci.b(:,2),[mintime:spacer:maxtime]);
highci = sigmoid(newfit.ci.b(:,1),[mintime:spacer:maxtime]);
main = sigmoid(newfit.b,[mintime:spacer:maxtime]);
errorbar(mintime:spacer:maxtime,main,lowci-main,highci-main,'k');

set(gca,'tickdir','out',...
  'box','off',...
  'xlim',[mintime maxtime],'xtick',[mintime:25:maxtime], ...
   'ylim',[0 1],'ytick',[0 .5 1], ...
  'PlotBoxAspectRatio',[1 1 1], ...
  'DataAspectRatioMode','auto', ...
  'FontName','Helvetica', ...
  'FontSize',12, ...
  'LineWidth',0.96, ...
  'TickLength',[.048 .048], ...
  'XTickMode','manual','YTickMode','manual','ZTickMode','manual','xlimmode','manual','ylimmode','manual','zlimmode','manual');

subplot(3,3,3)
hold on

plot(newmot.c,newvel.c,'k.','markersize',2,'markerfacecolor',[.6 .6 .6],'markeredgecolor',[.6 .6 .6]);

lowci = sigmoid(newfit.ci.c(:,2),[mintime:spacer:maxtime]);
highci = sigmoid(newfit.ci.c(:,1),[mintime:spacer:maxtime]);
main = sigmoid(newfit.c,[mintime:spacer:maxtime]);
errorbar(mintime:spacer:maxtime,main,lowci-main,highci-main,'k');

set(gca,'tickdir','out',...
  'box','off',...
  'xlim',[mintime maxtime],'xtick',[mintime:25:maxtime], ...
  'ylim',[0 1],'ytick',[0 .5 1], ...
  'PlotBoxAspectRatio',[1 1 1], ...
  'DataAspectRatioMode','auto', ...
  'FontName','Helvetica', ...
  'FontSize',12, ...
  'LineWidth',0.96, ...
  'TickLength',[.048 .048], ...
  'XTickMode','manual','YTickMode','manual','ZTickMode','manual','xlimmode','manual','ylimmode','manual','zlimmode','manual');

subplot(3,3,4)
hold on

plot(oldmot.a,oldvel.a,'k.','markersize',2,'markerfacecolor',[.6 .6 .6],'markeredgecolor',[.6 .6 .6]);

lowci = sigmoid(oldfit.ci.a(:,2),[mintime:spacer:maxtime]);
highci = sigmoid(oldfit.ci.a(:,1),[mintime:spacer:maxtime]);
main = sigmoid(oldfit.a,[mintime:spacer:maxtime]);
errorbar(mintime:spacer:maxtime,main,lowci-main,highci-main,'k');


set(gca,'tickdir','out',...
  'box','off',...
  'xlim',[mintime maxtime],'xtick',[mintime:25:maxtime], ...
  'ylim',[0 1],'ytick',[0 .5 1], ...
  'PlotBoxAspectRatio',[1 1 1], ...
  'DataAspectRatioMode','auto', ...
  'FontName','Helvetica', ...
  'FontSize',12, ...
  'LineWidth',0.96, ...
  'TickLength',[.048 .048], ...
  'XTickMode','manual','YTickMode','manual','ZTickMode','manual','xlimmode','manual','ylimmode','manual','zlimmode','manual');

subplot(3,3,5)
hold on

plot(oldmot.b,oldvel.b,'k.','markersize',2,'markerfacecolor',[.6 .6 .6],'markeredgecolor',[.6 .6 .6]);

lowci = sigmoid(oldfit.ci.b(:,2),[mintime:spacer:maxtime]);
highci = sigmoid(oldfit.ci.b(:,1),[mintime:spacer:maxtime]);

main = sigmoid(oldfit.b,[mintime:spacer:maxtime]);
errorbar(mintime:spacer:maxtime,main,lowci-main,highci-main,'k');


%plot(mintime:maxtime,sigmoid(cbs.stats.b.oldbeta,mintime:maxtime),'k','linewidth',0.96);
%plot(mintime:maxtime,sigmoid(cbs.stats.b.oldci(:,1),mintime:maxtime),'k','linewidth',0.96);
%plot(mintime:maxtime,sigmoid(cbs.stats.b.oldci(:,2),mintime:maxtime),'k','linewidth',0.96);

set(gca,'tickdir','out',...
  'box','off',...
  'xlim',[mintime maxtime],'xtick',[mintime:25:maxtime], ...
   'ylim',[0 1],'ytick',[0 .5 1], ...
  'PlotBoxAspectRatio',[1 1 1], ...
  'DataAspectRatioMode','auto', ...
  'FontName','Helvetica', ...
  'FontSize',12, ...
  'LineWidth',0.96, ...
  'TickLength',[.048 .048], ...
  'XTickMode','manual','YTickMode','manual','ZTickMode','manual','xlimmode','manual','ylimmode','manual','zlimmode','manual');

subplot(3,3,6)
hold on

plot(oldmot.c,oldvel.c,'k.','markersize',2,'markerfacecolor',[.6 .6 .6],'markeredgecolor',[.6 .6 .6]);

lowci = sigmoid(oldfit.ci.c(:,2),[mintime:spacer:maxtime]);
highci = sigmoid(oldfit.ci.c(:,1),[mintime:spacer:maxtime]);

main = sigmoid(oldfit.c,[mintime:spacer:maxtime]);
errorbar(mintime:spacer:maxtime,main,lowci-main,highci-main,'k');


%plot(mintime:maxtime,sigmoid(cbs.stats.c.oldbeta,mintime:maxtime),'k','linewidth',0.96);
%plot(mintime:maxtime,sigmoid(cbs.stats.c.oldci(:,1),mintime:maxtime),'k','linewidth',0.96);
%plot(mintime:maxtime,sigmoid(cbs.stats.c.oldci(:,2),mintime:maxtime),'k','linewidth',0.96);

set(gca,'tickdir','out',...
  'box','off',...
  'xlim',[mintime maxtime],'xtick',[mintime:25:maxtime], ...
   'ylim',[0 1],'ytick',[0 .5 1], ...
  'PlotBoxAspectRatio',[1 1 1], ...
  'DataAspectRatioMode','auto', ...
  'FontName','Helvetica', ...
  'FontSize',12, ...
  'LineWidth',0.96, ...
  'TickLength',[.048 .048], ...
  'XTickMode','manual','YTickMode','manual','ZTickMode','manual','xlimmode','manual','ylimmode','manual','zlimmode','manual');


subplot(3,3,7)
hold on

plot(typeamot.a,typeavel.a,'k.','markersize',2,'markerfacecolor',[.6 .6 .6],'markeredgecolor',[.6 .6 .6]);
plot(bindex(2:end-1),typeamean.a(2:end-1),'k','linewidth',3)

new = sigmoid(newfit.a,mintime:maxtime);
old = sigmoid(oldfit.a,mintime:maxtime);
plot(mintime:maxtime,new+old,'k--','linewidth',3);


set(gca,'tickdir','out',...
  'box','off',...
  'xlim',[mintime maxtime],'xtick',[mintime:25:maxtime], ...
  'ylim',[0.25 1.25],'ytick',[0.25 .75  1.25], ...
  'PlotBoxAspectRatio',[1 1 1], ...
  'DataAspectRatioMode','auto', ...
  'FontName','Helvetica', ...
  'FontSize',12, ...
  'LineWidth',0.96, ...
  'TickLength',[.048 .048], ...
  'XTickMode','manual','YTickMode','manual','ZTickMode','manual','xlimmode','manual','ylimmode','manual','zlimmode','manual');

subplot(3,3,8)
hold on

plot(typeamot.b,typeavel.b,'k.','markersize',2,'markerfacecolor',[.6 .6 .6],'markeredgecolor',[.6 .6 .6]);
plot(bindex(2:end-1),typeamean.b(2:end-1),'k','linewidth',3)

new = sigmoid(newfit.b,mintime:maxtime);
old = sigmoid(oldfit.b,mintime:maxtime);
plot(mintime:maxtime,new+old,'k--','linewidth',3);

set(gca,'tickdir','out',...
  'box','off',...
  'xlim',[mintime maxtime],'xtick',[mintime:25:maxtime], ...
  'ylim',[0.25 1.25],'ytick',[0.25 .75 1.25], ...
  'PlotBoxAspectRatio',[1 1 1], ...
  'DataAspectRatioMode','auto', ...
  'FontName','Helvetica', ...
  'FontSize',12, ...
  'LineWidth',0.96, ...
  'TickLength',[.048 .048], ...
  'XTickMode','manual','YTickMode','manual','ZTickMode','manual','xlimmode','manual','ylimmode','manual','zlimmode','manual');

subplot(3,3,9)
hold on

plot(typeamot.c,typeavel.c,'k.','markersize',2,'markerfacecolor',[.6 .6 .6],'markeredgecolor',[.6 .6 .6]);
plot(bindex(2:end-1),typeamean.c(2:end-1),'k','linewidth',3)

new = sigmoid(newfit.c,mintime:maxtime);
old = sigmoid(oldfit.c,mintime:maxtime);
plot(mintime:maxtime,new+old,'k--','linewidth',3);


set(gca,'tickdir','out',...
  'box','off',...
  'xlim',[mintime maxtime],'xtick',[mintime:25:maxtime], ...
  'ylim',[0.25 1.25],'ytick',[0.25 .75 1.25], ...
  'PlotBoxAspectRatio',[1 1 1], ...
  'DataAspectRatioMode','auto', ...
  'FontName','Helvetica', ...
  'FontSize',12, ...
  'LineWidth',0.96, ...
  'TickLength',[.048 .048], ...
  'XTickMode','manual','YTickMode','manual','ZTickMode','manual','xlimmode','manual','ylimmode','manual','zlimmode','manual');



