% prepare the data
cbs = preptypes(cbs);
mos = preptypes(mos);
pus = preptypes(pus);
qus = preptypes(qus);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% figure 2B -- Example with one monkey, all data %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

h = figure
subplot(2,3,1)
hold on
plot(cbs.summary.full.posdata(find(cbs.summary.full.side == 'r')),cbs.summary.full.veldata(find(cbs.summary.full.side == 'r')),'kd','markersize',2,'markerfacecolor','k','markeredgecolor','k');
plot(cbs.summary.full.posdata(find(cbs.summary.full.side == 'l')),cbs.summary.full.veldata(find(cbs.summary.full.side == 'l')),'kd','markersize',2,'markerfacecolor',[.6 .6 .6],'markeredgecolor',[.6 .6 .6]);

plot(cbs.summary.full.meanpos([1 3 5]),cbs.summary.full.meanvel([1 3 5]),'kd','markersize',6,'linewidth',0.96,'markerfacecolor','w','markeredgecolor','k');
plot(cbs.summary.full.meanpos([2 4 6]),cbs.summary.full.meanvel([2 4 6]),'kd','markersize',6,'linewidth',0.96,'markerfacecolor','w','markeredgecolor','k');


set(gca,'tickdir','out',...
  'box','off',...
  'xlim',[0 15],'xtick',[0 5 10 15], ...
  'ylim',[-15 15],'ytick',[-15 -10 -5 0 5 10 15], ...
  'PlotBoxAspectRatio',[1 1 1], ...
  'DataAspectRatioMode','auto', ...
  'FontName','Helvetica', ...
  'FontSize',12, ...
  'LineWidth',0.96, ...
  'TickLength',[.048 .048], ...
  'XTickMode','manual','YTickMode','manual','ZTickMode','manual','xlimmode','manual','ylimmode','manual','zlimmode','manual');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% figure 2C -- all monkeys, summary data %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

subplot(2,3,2)
hold on

errorbar(cbs.summary.meanpos,cbs.summary.meanvel,cbs.summary.stdvel,cbs.summary.stdvel,'kd','linestyle','-','color',[.6 .6 .6],'markerfacecolor',[1 1 1],'markeredgecolor','k');
errorbar(mos.summary.meanpos,mos.summary.meanvel,mos.summary.stdvel,mos.summary.stdvel,'ko','linestyle','-','color',[.6 .6 .6],'markerfacecolor',[1 1 1],'markeredgecolor','k');

errorbar(pus.summary.meanpos,pus.summary.meanvel,pus.summary.stdvel,pus.summary.stdvel,'ks','linestyle','-','color',[.6 .6 .6],'markerfacecolor',[1 1 1],'markeredgecolor','k');
errorbar(qus.summary.meanpos,qus.summary.meanvel,qus.summary.stdvel,qus.summary.stdvel,'k^','linestyle','-','color',[.6 .6 .6],'markerfacecolor',[1 1 1],'markeredgecolor','k');

set(gca,'tickdir','out',...
  'box','off',...
  'xlim',[0 15],'xtick',[0 5 10 15], ...
  'ylim',[0 15],'ytick',[0 5 10 15], ...
  'PlotBoxAspectRatio',[1 1 1], ...
  'DataAspectRatioMode','auto', ...
  'FontName','Helvetica', ...
  'FontSize',12, ...
  'LineWidth',0.96, ...
  'TickLength',[.048 .048], ...
  'XTickMode','manual','YTickMode','manual','ZTickMode','manual','xlimmode','manual','ylimmode','manual','zlimmode','manual');


subplot(2,3,3)
hold on

errorbar(cbs.summary.meanpos,cbs.summary.oldmeanvel,cbs.summary.oldstdvel,cbs.summary.oldstdvel,'kd','linestyle','-','color',[.6 .6 .6],'markerfacecolor',[1 1 1],'markeredgecolor','k');
errorbar(mos.summary.meanpos,mos.summary.oldmeanvel,mos.summary.oldstdvel,mos.summary.oldstdvel,'ko','linestyle','-','color',[.6 .6 .6],'markerfacecolor',[1 1 1],'markeredgecolor','k');

errorbar(pus.summary.meanpos,pus.summary.oldmeanvel,pus.summary.oldstdvel,pus.summary.oldstdvel,'ks','linestyle','-','color',[.6 .6 .6],'markerfacecolor',[1 1 1],'markeredgecolor','k');
errorbar(qus.summary.meanpos,qus.summary.oldmeanvel,qus.summary.oldstdvel,qus.summary.oldstdvel,'k^','linestyle','-','color',[.6 .6 .6],'markerfacecolor',[1 1 1],'markeredgecolor','k');


set(gca,'tickdir','out',...
  'box','off',...
  'xlim',[0 15],'xtick',[0 5 10 15], ...
  'ylim',[0 15],'ytick',[0 5 10 15], ...
  'PlotBoxAspectRatio',[1 1 1], ...
  'DataAspectRatioMode','auto', ...
  'FontName','Helvetica', ...
  'FontSize',12, ...
  'LineWidth',0.96, ...
  'TickLength',[.048 .048], ...
  'XTickMode','manual','YTickMode','manual','ZTickMode','manual','xlimmode','manual','ylimmode','manual','zlimmode','manual');



%%%%%%%%%%%%%%%%%%%%%%
% summary statistics %
%%%%%%%%%%%%%%%%%%%%%%

disp(['mean slope non-normalized data = ', num2str(mean([cbs.stats.slope mos.stats.slope pus.stats.slope qus.stats.slope]))])
disp(['std slope non-normalized data = ', num2str(std([cbs.stats.slope mos.stats.slope pus.stats.slope qus.stats.slope]))])
disp(['p slope non-normalized data = ', num2str(std([cbs.stats.pslope mos.stats.pslope pus.stats.pslope qus.stats.pslope]))])

disp(['mean y-int non-normalized data = ', num2str(mean([cbs.stats.yint mos.stats.yint pus.stats.yint qus.stats.yint]))])
disp(['std y-int non-normalized data = ', num2str(std([cbs.stats.yint mos.stats.yint pus.stats.yint qus.stats.yint]))])
disp(['p yint slope non-normalized data = ', num2str(std([cbs.stats.pyint mos.stats.pyint pus.stats.pyint qus.stats.pyint]))])

disp(['o mean slope non-normalized data = ', num2str(mean([cbs.stats.oldslope mos.stats.oldslope pus.stats.oldslope qus.stats.oldslope]))])
disp(['o std slope non-normalized data = ', num2str(std([cbs.stats.oldslope mos.stats.oldslope pus.stats.oldslope qus.stats.oldslope]))])
disp(['o p slope non-normalized data = ', num2str(std([cbs.stats.oldpslope mos.stats.oldpslope pus.stats.oldpslope qus.stats.oldpslope]))])

disp(['o mean y-int non-normalized data = ', num2str(mean([cbs.stats.oldyint mos.stats.oldyint pus.stats.oldyint qus.stats.oldyint]))])
disp(['o std y-int non-normalized data = ', num2str(std([cbs.stats.oldyint mos.stats.oldyint pus.stats.oldyint qus.stats.oldyint]))])
disp(['o p yint slope non-normalized data = ', num2str(std([cbs.stats.oldpyint mos.stats.oldpyint pus.stats.oldpyint qus.stats.oldpyint]))])


cbh = preptypeh(cbh);
moh = preptypeh(moh);
puh = preptypeh(puh);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% figure 2e -- Example with one monkey, all data %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%



subplot(2,3,4)
hold on
plot(puh.summary.full.posdata(find(puh.summary.full.side == 'u')),puh.summary.full.veldata(find(puh.summary.full.side == 'u')),'ks','markersize',2,'markerfacecolor','k','markeredgecolor','k');
plot(puh.summary.full.posdata(find(puh.summary.full.side == 'd')),puh.summary.full.veldata(find(puh.summary.full.side == 'd')),'ks','markersize',2,'markerfacecolor',[.6 .6 .6],'markeredgecolor',[.6 .6 .6]);

plot(puh.summary.full.meanpos([1 3 5]),puh.summary.full.meanvel([2 4 6]),'s','markersize',6,'linewidth',0.96,'markerfacecolor','w','markeredgecolor','k');
plot(puh.summary.full.meanpos([2 4 6]),puh.summary.full.meanvel([1 3 5]),'s','markersize',6,'linewidth',0.96,'markerfacecolor','w','markeredgecolor','k');

set(gca,'tickdir','out',...
  'box','off',...
  'xlim',[0 10],'xtick',[0 5 10], ...
  'ylim',[-20 20],'ytick',[-20 -10 0 10 20], ...
  'PlotBoxAspectRatio',[1 1 1], ...
  'DataAspectRatioMode','auto', ...
  'FontName','Helvetica', ...
  'FontSize',12, ...
  'LineWidth',0.96, ...
  'TickLength',[.048 .048], ...
  'XTickMode','manual','YTickMode','manual','ZTickMode','manual','xlimmode','manual','ylimmode','manual','zlimmode','manual');


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% figure 2f -- all monkeys, summary data %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

subplot(2,3,5)
hold on

errorbar(cbh.summary.meanpos,cbh.summary.meanvel,cbh.summary.stdvel,cbh.summary.stdvel,'kd','linestyle','-','color',[.6 .6 .6],'markerfacecolor',[1 1 1],'markeredgecolor','k');
errorbar(moh.summary.meanpos,moh.summary.meanvel,moh.summary.stdvel,moh.summary.stdvel,'ko','linestyle','-','color',[.6 .6 .6],'markerfacecolor',[1 1 1],'markeredgecolor','k');

errorbar(puh.summary.meanpos,puh.summary.meanvel,puh.summary.stdvel,puh.summary.stdvel,'ks','linestyle','-','color',[.6 .6 .6],'markerfacecolor',[1 1 1],'markeredgecolor','k');


set(gca,'tickdir','out',...
  'box','off',...
  'xlim',[0 10],'xtick',[0 5 10], ...
  'ylim',[0 15],'ytick',[0 5 10 15], ...
  'PlotBoxAspectRatio',[1 1 1], ...
  'DataAspectRatioMode','auto', ...
  'FontName','Helvetica', ...
  'FontSize',12, ...
  'LineWidth',0.96, ...
  'TickLength',[.048 .048], ...
  'XTickMode','manual','YTickMode','manual','ZTickMode','manual','xlimmode','manual','ylimmode','manual','zlimmode','manual');

subplot(2,3,6)
hold on

errorbar(cbh.summary.meanpos,cbh.summary.oldmeanvel,cbh.summary.oldstdvel,cbh.summary.oldstdvel,'kd','linestyle','-','color',[.6 .6 .6],'markerfacecolor',[1 1 1],'markeredgecolor','k');
errorbar(moh.summary.meanpos,moh.summary.oldmeanvel,moh.summary.oldstdvel,moh.summary.oldstdvel,'ko','linestyle','-','color',[.6 .6 .6],'markerfacecolor',[1 1 1],'markeredgecolor','k');

errorbar(puh.summary.meanpos,puh.summary.oldmeanvel,puh.summary.oldstdvel,puh.summary.oldstdvel,'ks','linestyle','-','color',[.6 .6 .6],'markerfacecolor',[1 1 1],'markeredgecolor','k');


set(gca,'tickdir','out',...
  'box','off',...
  'xlim',[0 10],'xtick',[0 5 10], ...
  'ylim',[0 15],'ytick',[0 5 10 15], ...
  'PlotBoxAspectRatio',[1 1 1], ...
  'DataAspectRatioMode','auto', ...
  'FontName','Helvetica', ...
  'FontSize',12, ...
  'LineWidth',0.96, ...
  'TickLength',[.048 .048], ...
  'XTickMode','manual','YTickMode','manual','ZTickMode','manual','xlimmode','manual','ylimmode','manual','zlimmode','manual');

%%%%%%%%%%%%%%%%%%%%%%
% summary statistics %
%%%%%%%%%%%%%%%%%%%%%%

disp(['h mean slope non-normalized data = ', num2str(mean([cbh.stats.slope moh.stats.slope puh.stats.slope]))])
disp(['h std slope non-normalized data = ', num2str(std([cbh.stats.slope moh.stats.slope puh.stats.slope]))])
disp(['h mean y-int non-normalized data = ', num2str(mean([cbh.stats.yint moh.stats.yint puh.stats.yint]))])
disp(['h std y-int non-normalized data = ', num2str(std([cbh.stats.yint moh.stats.yint puh.stats.yint]))])

disp(['h mean slope non-normalized data = ', num2str(mean([cbh.stats.oldslope moh.stats.oldslope puh.stats.oldslope]))])
disp(['h std slope non-normalized data = ', num2str(std([cbh.stats.oldslope moh.stats.oldslope puh.stats.oldslope]))])
disp(['h mean y-int non-normalized data = ', num2str(mean([cbh.stats.oldyint moh.stats.oldyint puh.stats.oldyint]))])
disp(['h std y-int non-normalized data = ', num2str(std([cbh.stats.oldyint moh.stats.oldyint puh.stats.oldyint]))])