cbu = preptypeu(cbu);
mou = preptypeu(mou);
puu = preptypeu(puu);
quu = preptypeu(quu);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% figure 7B -- Example with one monkey, all data %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

h = figure
subplot(1,3,1)
hold on
plot(quu.summary.full.posdata(find(quu.summary.full.side == 'r')),quu.summary.full.veldata(find(quu.summary.full.side == 'r')),'^','markersize',2,'markerfacecolor','k','markeredgecolor','k');
plot(quu.summary.full.posdata(find(quu.summary.full.side == 'l')),quu.summary.full.veldata(find(quu.summary.full.side == 'l')),'^','markersize',2,'markerfacecolor',[.6 .6 .6],'markeredgecolor',[.6 .6 .6]);

plot(quu.summary.full.meanpos([1 3 5]),quu.summary.full.meanvel([1 3 5]),'k^','markersize',6,'linewidth',0.96,'markerfacecolor','w','markeredgecolor',[.6 .6 .6]);
plot(quu.summary.full.meanpos([2 4 6]),quu.summary.full.meanvel([2 4 6]),'k^','markersize',6,'linewidth',0.96,'markerfacecolor','w','markeredgecolor','k');


set(gca,'tickdir','out',...
  'box','off',...
  'xlim',[0 15],'xtick',[0 5 10 15], ...
  'ylim',[-20 20],'ytick',[-20 -15 -10 -5 0 5 10 15 20], ...
  'PlotBoxAspectRatio',[1 1 1], ...
  'DataAspectRatioMode','auto', ...
  'FontName','Helvetica', ...
  'FontSize',12, ...
  'LineWidth',0.96, ...
  'TickLength',[.048 .048], ...
  'XTickMode','manual','YTickMode','manual','ZTickMode','manual','xlimmode','manual','ylimmode','manual','zlimmode','manual');


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% figure 7C -- all monkeys, summary data %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
subplot(1,3,2)
hold on

errorbar(cbu.summary.meanpos,cbu.summary.meanvel,cbu.summary.stdvel,cbu.summary.stdvel,'kd','linestyle','-','color',[.6 .6 .6],'markerfacecolor',[1 1 1],'markeredgecolor','k');
errorbar(mou.summary.meanpos,mou.summary.meanvel,mou.summary.stdvel,mou.summary.stdvel,'ko','linestyle','-','color',[.6 .6 .6],'markerfacecolor',[1 1 1],'markeredgecolor','k');

errorbar(puu.summary.meanpos,puu.summary.meanvel,puu.summary.stdvel,puu.summary.stdvel,'ks','linestyle','-','color',[.6 .6 .6],'markerfacecolor',[1 1 1],'markeredgecolor','k');
errorbar(quu.summary.meanpos,quu.summary.meanvel,quu.summary.stdvel,quu.summary.stdvel,'k^','linestyle','-','color',[.6 .6 .6],'markerfacecolor',[1 1 1],'markeredgecolor','k');

set(gca,'tickdir','out',...
  'box','off',...
  'xlim',[0 15],'xtick',[0 5 10 15], ...
  'ylim',[0 15],'ytick',[0 5 10 15], ...
  'PlotBoxAspectRatio',[1 1 1], ...
  'DataAspectRatioMode','auto', ...
  'FontName','Helvetica', ...
  'FontSize',12, ...
  'LineWidth',0.96, ...
  'TickLength',[.048 .048], ...
  'XTickMode','manual','YTickMode','manual','ZTickMode','manual','xlimmode','manual','ylimmode','manual','zlimmode','manual');

subplot(1,3,3)
hold on

errorbar(cbu.summary.meanpos,cbu.summary.oldmeanvel,cbu.summary.oldstdvel,cbu.summary.oldstdvel,'kd','linestyle','-','color',[.6 .6 .6],'markerfacecolor',[1 1 1],'markeredgecolor','k');
errorbar(mou.summary.meanpos,mou.summary.oldmeanvel,mou.summary.oldstdvel,mou.summary.oldstdvel,'ko','linestyle','-','color',[.6 .6 .6],'markerfacecolor',[1 1 1],'markeredgecolor','k');

errorbar(puu.summary.meanpos,puu.summary.oldmeanvel,puu.summary.oldstdvel,puu.summary.oldstdvel,'ks','linestyle','-','color',[.6 .6 .6],'markerfacecolor',[1 1 1],'markeredgecolor','k');
errorbar(quu.summary.meanpos,quu.summary.oldmeanvel,quu.summary.oldstdvel,quu.summary.oldstdvel,'k^','linestyle','-','color',[.6 .6 .6],'markerfacecolor',[1 1 1],'markeredgecolor','k');

set(gca,'tickdir','out',...
  'box','off',...
  'xlim',[0 15],'xtick',[0 5 10 15], ...
  'ylim',[0 15],'ytick',[0 5 10 15], ...
  'PlotBoxAspectRatio',[1 1 1], ...
  'DataAspectRatioMode','auto', ...
  'FontName','Helvetica', ...
  'FontSize',12, ...
  'LineWidth',0.96, ...
  'TickLength',[.048 .048], ...
  'XTickMode','manual','YTickMode','manual','ZTickMode','manual','xlimmode','manual','ylimmode','manual','zlimmode','manual');

disp(['mean slope non-normalized data = ', num2str(mean([cbu.stats.slope mou.stats.slope puu.stats.slope quu.stats.slope]))])
disp(['std slope non-normalized data = ', num2str(std([cbu.stats.slope mou.stats.slope puu.stats.slope quu.stats.slope]))])
disp(['p slope non-normalized data = ', num2str(std([cbu.stats.pslope mou.stats.pslope puu.stats.pslope quu.stats.pslope]))])

disp(['mean y-int non-normalized data = ', num2str(mean([cbu.stats.yint mou.stats.yint puu.stats.yint quu.stats.yint]))])
disp(['std y-int non-normalized data = ', num2str(std([cbu.stats.yint mou.stats.yint puu.stats.yint quu.stats.yint]))])
disp(['p yint slope non-normalized data = ', num2str(std([cbu.stats.pyint mou.stats.pyint puu.stats.pyint quu.stats.pyint]))])

disp(['o mean slope non-normalized data = ', num2str(mean([cbu.stats.oldslope mou.stats.oldslope puu.stats.oldslope quu.stats.oldslope]))])
disp(['o std slope non-normalized data = ', num2str(std([cbu.stats.oldslope mou.stats.oldslope puu.stats.oldslope quu.stats.oldslope]))])
disp(['o p slope non-normalized data = ', num2str(std([cbu.stats.oldpslope mou.stats.oldpslope puu.stats.oldpslope quu.stats.oldpslope]))])

disp(['o mean y-int non-normalized data = ', num2str(mean([cbu.stats.oldyint mou.stats.oldyint puu.stats.oldyint quu.stats.oldyint]))])
disp(['o std y-int non-normalized data = ', num2str(std([cbu.stats.oldyint mou.stats.oldyint puu.stats.oldyint quu.stats.oldyint]))])
disp(['o p yint slope non-normalized data = ', num2str(std([cbu.stats.oldpyint mou.stats.oldpyint puu.stats.oldpyint quu.stats.oldpyint]))])
